#!/bin/bash

REVEL_PID="${OPENSHIFT_DATA_DIR}revel.pid"
REVEL_LOG="${OPENSHIFT_LOG_DIR}revel.log"

echo -n "Shutting down: "
if [ ! -f $REVEL_PID ]; then
   echo "revel not running"
   exit 0
fi

PID=`cat $REVEL_PID 2>/dev/null`
echo -n "revel (pid $PID) "
CNT=0
kill $PID 2>/dev/null;
# wait for max. 20 seconds to finish
while [[ -e /proc/$PID && $CNT -lt 20 ]]; do
   echo -n "."
   let CNT=CNT+1
   sleep 1
done
# kill the process if it's still running
if [ -e /proc/$PID ]; then
   echo " KILLING PROCESS!"
   kill -9 $PID 2>/dev/null
else
   echo " stopped successfully"
fi
rm -f $REVEL_PID